let categorizedGames={'multiplayer':document.createElement('div'),'car':document.createElement('div'),'casual':document.createElement('div'),'action':document.createElement('div'),'shooting':document.createElement('div'),'puzzle':document.createElement('div'),'classic':document.createElement('div'),'sport':document.createElement('div'),'clicker':document.createElement('div'),'escape':document.createElement('div'),'2':document.createElement('div'),'horror':document.createElement('div'),'hard':document.createElement('div'),'music':document.createElement('div'),'new':document.createElement('div'),'flash':document.createElement('div')}
let token;let interval;let shouldAutoSwitch=true;let slideIndex=1;const slides=document.getElementsByClassName('featureSlot');const switchSlide=(n)=>{if(n>slides.length){slideIndex=1;}
if(n<1){slideIndex=slides.length;}
for(i=0;i<slides.length;i++){slides[i].style.display='none';}
slides[slideIndex-1].style.display='';};const plusSlides=(n)=>{shouldAutoSwitch=false;switchSlide((slideIndex+=n));};const autoPlusSlides=(n)=>{switchSlide((slideIndex+=n));};const autoSwitch=()=>{if(shouldAutoSwitch){setTimeout(()=>{if(shouldAutoSwitch){autoPlusSlides(1);autoSwitch();}},2500);}};switchSlide(slideIndex);autoSwitch();let games;let sorted;window.addEventListener('load',async()=>{document.getElementById('gamesnav').classList.add('selected');let gamesRes=await fetcher('/games');games=await gamesRes.json();let featuresRes=await fetcher('/features');features=await featuresRes.json();for(let feature of features)
{let index=features.indexOf(feature);let featureEle=document.getElementById('feature-'+(index+1));featureEle.children[0].children[1].innerText=feature.game;featureEle.children[1].onclick=()=>{window.open(feature.url,'_self')};featureEle.style.backgroundImage=`url(./assets/images/featuredimg/${feature.image})`;}
loadGames();let response=await fetcher(`/auth/check`);if(response.status==401||response.status==403){token=false;document.getElementById('timerText').innerHTML='<a href="/signup.php">Sign up</a> to collect your daily reward!';const suggestionEle=document.getElementById('scisuggests');suggestionEle.textContent='';for(let x=0;x<6;x++){let randGame=randomProperty(games);let gameBtn=createGameButton(randGame,'suggested',false);suggestionEle.appendChild(gameBtn);}}else{let json=await response.json();setPointsDisplay(json.points||0);token=true;loadRewards();suggestGames();}
loadPartners();});async function loadGames(){const sortObject=(obj)=>Object.keys(obj).sort().reduce((res,key)=>((res[key]=obj[key]),res),{});sorted=sortObject(games);const weekAgo=new Date();weekAgo.setDate(weekAgo.getDate()-7*3);for(let name in sorted){const gameDate=new Date(sorted[name].date_added);if(gameDate>weekAgo){categorizedGames.new?.appendChild(createGameButton(name,'',true))}
for(let tag of sorted[name].tags){categorizedGames[tag]?.appendChild(createGameButton(name,'',true))}}
if(categorizedGames.new.children.length>0){document.getElementById('newGamesLabel').style.display='';document.getElementById('newGamesHorizontalCon').style.display='';}
for(let categorizedGame in categorizedGames){categorizedGames[categorizedGame].className='gamesCon';document.getElementById(categorizedGame+'GamesHorizontalCon').appendChild(categorizedGames[categorizedGame]);}
loadPopularGames();loadLikedGames();addArrowListeners();findLazyImages();}
async function loadPopularGames(){let popGamesRes=await fetcher(`/stats/games/popular`);if(popGamesRes.status==200){const populargamesContainer=document.getElementById('popularGamesCon');let popularGames=await popGamesRes.json();for(let i=0;i<15;i++){if(popularGames[i].game){populargamesContainer.appendChild(createGameButton(popularGames[i].game,'hot'));}}}}
async function loadLikedGames(){const likedGamesContainer=document.getElementById('likedGamesCon');let userLikedRes=await fetcher(`/profile/liked/get`);if(userLikedRes.status==200){let likedgames=await userLikedRes.json();if(likedgames.length>0){document.getElementById('likedGamesLabel').style.display='';document.getElementById('likedGamesHorizontalCon').style.display='';for(like in likedgames){likedGamesContainer.appendChild(createGameButton(likedgames[like]));}}}else{let likedgames=JSON.parse(localStorage.getItem('likedGames'));if(Object.keys(likedgames).length>5){document.getElementById('likedGamesLabel').style.display='';document.getElementById('likedGamesHorizontalCon').style.display='';for(like in likedgames){if(likedgames[like]){likedGamesContainer.appendChild(createGameButton(like));}}}}}
async function loadPartners(){let partnersRes=await fetcher(`/partners`);let partners=await partnersRes.json();for(let x=0;x<partners.length;x++){const backgroundImg=`data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1' height='1'%3E%3Crect width='100%25' height='100%25' fill='%23340060'/%3E%3C/svg%3E`;const name=partners[x].name;const image=partners[x].image;const website=partners[x].website;let partnerEle=document.createElement('div');partnerEle.tagName=name;partnerEle.id='gameDiv';partnerEle.addEventListener('click',()=>{window.open(website,'_blank')});let imageContainer=document.createElement('div');imageContainer.classList='imageCon partner';let img=document.createElement('img');img.classList='lazy partner';img.setAttribute('data-src',image);img.src=backgroundImg;img.alt=`Totally Science Partner ${name}`;img.title=`Totally Science Partner ${name}`;let nameEle=document.createElement('h1');nameEle.className='innerGameDiv';nameEle.innerText=name;imageContainer.appendChild(img);partnerEle.appendChild(imageContainer);partnerEle.appendChild(nameEle);document.getElementById(`PartnersCon`).appendChild(partnerEle);}
findLazyImages();}
async function loadRewards(){let rewardRes=await fetcher(`/points/reward/check`);let text=await rewardRes.text();let json=JSON.parse(text);if(json.isReady){let points=100;if(json.rewardDay>=6){points=1000;}
document.getElementById('timerText').innerHTML=`<a onclick="claimReward()" href="javascript:void(null)">Click here</a> to collect your daily reward of ${points} pts!`;}else{startTimer(json.rewardTime);}
animateBar(json.rewardDay);}
function startTimer(endTime){clearInterval(interval);document.getElementById('timerText').innerHTML='<span class="loader"></span>Daily Reward In <span id="rewardTimer"></span>';interval=setInterval(()=>{let currentTime=Math.floor(Date.now()/1000);let remainingTime=endTime-currentTime;if(remainingTime<0){document.getElementById('rewardTimer').innerText='00:00:00';clearInterval(interval);return;}
let seconds=Math.floor(remainingTime%60).toString().padStart(2,'0');let minutes=Math.floor((remainingTime/60)%60).toString().padStart(2,'0');let hours=Math.floor((remainingTime/(60*60))%24).toString().padStart(2,'0');document.getElementById('rewardTimer').innerText=hours+':'+minutes+':'+seconds;},1000);}
function animateBar(day){const rewardBar=document.getElementById('rewardDayBar');let w=(100/7)*(day+1);rewardBar.style.width=`${w}%`;rewardBar.style.borderTopRightRadius=`0px`;rewardBar.style.borderBottomRightRadius=`0px`;if(day==6){rewardBar.style.borderTopRightRadius=`15px`;rewardBar.style.borderBottomRightRadius=`15px`;}}
async function claimReward(){document.getElementById('timerText').innerHTML='<span class="loader"></span>';let res=await fetcher(`/points/reward/claim`);if(res.status==200){let text=await res.text();let json=JSON.parse(text);startTimer(json.rewardTime);animateBar(json.rewardDay);let currentVal=document.getElementById('pointsDisplay').innerText;counter('pointsDisplay',parseInt(currentVal),parseInt(currentVal)+parseInt(json.points),2000);if(json.points==0){document.getElementById('timerText').innerHTML='Oh no! Your daily reward expired.<span class="loader"></span> Next Daily Reward In <span id="rewardTimer"></span>';}}else{location.href='signup.php';}}
async function suggestGames(){let res=await fetcher(`/profile/pinned/get`);let text=await res.text();let pinnedGames=text.split(';');pinnedGames=pinnedGames.slice(1);let randomGames=[];for(let x=0;x<3;x++){let randGame=randomProperty(games);while(randomGames.includes(randGame)||pinnedGames.includes(randGame)){randGame=randomProperty(games);}
randomGames.push(randGame);}
let totalPinned=pinnedGames.length;if(pinnedGames.length<3){let generateGames=3-pinnedGames.length;for(let i=0;i<generateGames;i++){let randGame=randomProperty(games);while(randomGames.includes(randGame)||pinnedGames.includes(randGame)){randGame=randomProperty(games);}
pinnedGames.push(randGame);}}
document.getElementById('scisuggests').innerHTML='';for(let i=0;i<3;i++){let game=randomGames[i];let gameBtn=createGameButton(game,'suggested',false);document.getElementById('scisuggests').appendChild(gameBtn);game=pinnedGames[i];if(i<=totalPinned-1){gameBtn=createGameButton(game,'pin',false);}else{gameBtn=createGameButton(game,'suggested',false);}
document.getElementById('scisuggests').append(gameBtn);}}
function createGameButton(game,pin,lazy){const data=games[game];if(data==null)return document.createElement('div');const weekAgo=new Date();weekAgo.setDate(weekAgo.getDate()-7*3);const gameDate=new Date(data.date_added);const onclick=`location.href = 'class.php?class=${game.replaceAll(' ','-')}'`;let gameDiv=document.createElement('div');gameDiv.setAttribute('tagName',game);gameDiv.id='gameDiv';gameDiv.classlist=data.tags.join(' ');gameDiv.setAttribute('onclick',onclick);if(pin=='pin'){let button=document.createElement('button');button.id='pin';let image=document.createElement('img');image.src='/assets/images/icons/coloredpin.avif';button.appendChild(image);gameDiv.appendChild(button);}else if(pin=='hot'){let button=document.createElement('button');button.id='newbanner';let image=document.createElement('img');image.src='assets/images/icons/hotbanner.avif';button.appendChild(image);gameDiv.appendChild(button);}else if(pin=='hidden'){gameDiv.style.display='none';}else if(pin!='suggested'){gameDiv.classList.add('all');}
if(gameDate>weekAgo){gameDiv.classList.add('new');let button=document.createElement('button');button.id='newbanner';let image=document.createElement('img');image.src='assets/images/icons/newbanner.avif';button.appendChild(image);gameDiv.appendChild(button);}
let backgroundImg=lazy?`data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1' height='1'%3E%3Crect width='100%25' height='100%25' fill='%23340060'/%3E%3C/svg%3E`:data.image;let lazyClass=lazy?'lazy':'';let imageContainer=document.createElement('div');imageContainer.className='imageCon';let img=document.createElement('img');img.setAttribute('data-src',data.image);img.src=backgroundImg;img.alt=`Totally Science ${game}`;img.title=`Totally Science ${game}`;img.className=lazyClass;imageContainer.appendChild(img);gameDiv.appendChild(imageContainer);let header=document.createElement('h1');header.className='innerGameDiv';header.innerText=game;gameDiv.appendChild(header);return gameDiv;}
async function addArrowListeners(){const leftArrows=document.getElementsByClassName('arrowLeftCon');const rightArrows=document.getElementsByClassName('arrowRightCon');for(let arrow of leftArrows){arrow.addEventListener('click',(e)=>{const parentElement=e.target.parentNode.parentNode;const gamesCon=parentElement.querySelectorAll('.gamesCon')[0];gamesCon.scrollLeft-=Math.min(gamesCon.scrollLeft,1100);});}
for(let arrow of rightArrows){arrow.addEventListener('click',(e)=>{const parentElement=e.target.parentNode.parentNode;const gamesCon=parentElement.querySelectorAll('.gamesCon')[0];const leftArrow=e.target.parentNode.parentNode.querySelectorAll('.arrowCon')[0];leftArrow.style+='visibility: visible';const remainingSpace=gamesCon.scrollWidth-gamesCon.clientWidth-gamesCon.scrollLeft;gamesCon.scrollLeft+=Math.min(remainingSpace,1100);});}}
async function findLazyImages(){const lazyImages=document.querySelectorAll('.lazy');const observer=new IntersectionObserver((entries)=>{entries.forEach((entry)=>{if(entry.isIntersecting){entry.target.src=entry.target.dataset.src;entry.target.classList.remove('lazy');observer.unobserve(entry.target);}});},{threshold:0.1,rootMargin:'500px 0px',});lazyImages.forEach((image)=>{observer.observe(image);});}